title: "UNAGI"
description: An interactive tool for analyzing single-cell omics data
baseurl: "/unagi" # the subpath of your site, e.g. /blog
url: "https://sshazeljiang.github.io"
permalink: pretty
#remote_theme: just-the-docs/just-the-docs
remote_theme: chrisrhymes/bulma-clean-theme

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true

back_to_top: true
back_to_top_text: "Back to top"

markdown: kramdown
kramdown:
  math_engine: katex
highlighter: rouge

footer_content: ""

aux_links:
  "UNGAI on GitHub":
    - "//github.com/Karlxy0511/IPF_Dashboard"

aux_links_new_tab: true
